import type { Vendor } from '@/types/audit'

export const VENDORS: Vendor[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    category: 'ai_assistant',
    description: 'General-purpose AI assistant by OpenAI',
    overlaps: ['claude', 'gemini'],
    plans: [
      {
        planName: 'Free',
        monthlyPricePerSeat: 0,
        flatMonthlyPrice: 0,
        annualMonthlyEquivalent: null,
        maxSeats: 1,
        minSeats: null,
        features: ['GPT-4o limited', 'Basic DALL-E', 'Limited web browsing'],
        bestFor: ['solo_developer'],
        sourceUrl: 'https://openai.com/chatgpt/pricing',
        lastVerified: '2025-01-15',
        notes: 'Rate limited access to GPT-4o',
      },
      {
        planName: 'Plus',
        monthlyPricePerSeat: 20,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: 1,
        minSeats: null,
        features: ['GPT-4o priority', 'DALL-E 3', 'Advanced data analysis', 'Custom GPTs'],
        bestFor: ['solo_developer'],
        sourceUrl: 'https://openai.com/chatgpt/pricing',
        lastVerified: '2025-01-15',
        notes: null,
      },
      {
        planName: 'Pro',
        monthlyPricePerSeat: 200,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: 1,
        minSeats: null,
        features: ['Unlimited GPT-4o', 'o1 pro mode', 'Extended thinking'],
        bestFor: ['solo_developer'],
        sourceUrl: 'https://openai.com/chatgpt/pricing',
        lastVerified: '2025-01-15',
        notes: 'Heavy usage only — most users do not need this tier',
      },
      {
        planName: 'Team',
        monthlyPricePerSeat: 30,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: 25,
        maxSeats: null,
        minSeats: 2,
        features: ['Everything in Plus', 'Team workspace', 'Admin console', 'Higher limits'],
        bestFor: ['small_team', 'mid_team'],
        sourceUrl: 'https://openai.com/chatgpt/pricing',
        lastVerified: '2025-01-15',
        notes: 'Annual billing: $25/seat/month',
      },
      {
        planName: 'Enterprise',
        monthlyPricePerSeat: 0,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: null,
        minSeats: null,
        features: ['Custom pricing', 'SSO', 'Advanced security', 'Dedicated support'],
        bestFor: ['large_team'],
        sourceUrl: 'https://openai.com/chatgpt/pricing',
        lastVerified: '2025-01-15',
        notes: 'Contact sales — not suitable for small teams',
      },
    ],
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'ai_assistant',
    description: 'AI assistant by Anthropic, strong at writing and analysis',
    overlaps: ['chatgpt', 'gemini'],
    plans: [
      {
        planName: 'Free',
        monthlyPricePerSeat: 0,
        flatMonthlyPrice: 0,
        annualMonthlyEquivalent: null,
        maxSeats: 1,
        minSeats: null,
        features: ['Claude 3.5 Haiku limited', 'Basic usage'],
        bestFor: ['solo_developer'],
        sourceUrl: 'https://www.anthropic.com/pricing',
        lastVerified: '2025-01-15',
        notes: 'Limited daily messages',
      },
      {
        planName: 'Pro',
        monthlyPricePerSeat: 20,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: 1,
        minSeats: null,
        features: ['Claude 3.5 Sonnet', 'Extended context', 'Priority access', 'Projects'],
        bestFor: ['solo_developer'],
        sourceUrl: 'https://www.anthropic.com/pricing',
        lastVerified: '2025-01-15',
        notes: null,
      },
      {
        planName: 'Team',
        monthlyPricePerSeat: 30,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: null,
        minSeats: 2,
        features: ['Everything in Pro', 'Team collaboration', 'Admin dashboard', 'Higher limits'],
        bestFor: ['small_team', 'mid_team'],
        sourceUrl: 'https://www.anthropic.com/pricing',
        lastVerified: '2025-01-15',
        notes: null,
      },
      {
        planName: 'Enterprise',
        monthlyPricePerSeat: 0,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: null,
        minSeats: null,
        features: ['Custom pricing', 'SSO', 'Audit logs', 'Dedicated support'],
        bestFor: ['large_team'],
        sourceUrl: 'https://www.anthropic.com/pricing',
        lastVerified: '2025-01-15',
        notes: 'Contact sales',
      },
    ],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    category: 'ai_coding',
    description: 'AI-native code editor built on VS Code',
    overlaps: ['github_copilot', 'windsurf'],
    plans: [
      {
        planName: 'Hobby',
        monthlyPricePerSeat: 0,
        flatMonthlyPrice: 0,
        annualMonthlyEquivalent: null,
        maxSeats: 1,
        minSeats: null,
        features: ['2000 completions/month', '50 slow requests', 'Basic AI features'],
        bestFor: ['solo_developer'],
        sourceUrl: 'https://www.cursor.com/pricing',
        lastVerified: '2025-01-15',
        notes: 'Free tier has meaningful limits',
      },
      {
        planName: 'Pro',
        monthlyPricePerSeat: 20,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: 16,
        maxSeats: 1,
        minSeats: null,
        features: ['Unlimited completions', '500 fast requests/month', 'GPT-4 & Claude access'],
        bestFor: ['solo_developer', 'small_team'],
        sourceUrl: 'https://www.cursor.com/pricing',
        lastVerified: '2025-01-15',
        notes: 'Annual billing: $16/month',
      },
      {
        planName: 'Business',
        monthlyPricePerSeat: 40,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: null,
        minSeats: null,
        features: ['Everything in Pro', 'SSO', 'Admin dashboard', 'Privacy mode enforced'],
        bestFor: ['small_team', 'mid_team', 'large_team'],
        sourceUrl: 'https://www.cursor.com/pricing',
        lastVerified: '2025-01-15',
        notes: 'Per seat pricing',
      },
    ],
  },
  {
    id: 'github_copilot',
    name: 'GitHub Copilot',
    category: 'ai_coding',
    description: 'AI pair programmer integrated into GitHub ecosystem',
    overlaps: ['cursor', 'windsurf'],
    plans: [
      {
        planName: 'Free',
        monthlyPricePerSeat: 0,
        flatMonthlyPrice: 0,
        annualMonthlyEquivalent: null,
        maxSeats: 1,
        minSeats: null,
        features: ['2000 completions/month', '50 chat messages/month'],
        bestFor: ['solo_developer'],
        sourceUrl: 'https://github.com/features/copilot#pricing',
        lastVerified: '2025-01-15',
        notes: 'Available to all GitHub users',
      },
      {
        planName: 'Pro',
        monthlyPricePerSeat: 10,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: 8.33,
        maxSeats: 1,
        minSeats: null,
        features: ['Unlimited completions', 'Unlimited chat', 'Multi-model support'],
        bestFor: ['solo_developer'],
        sourceUrl: 'https://github.com/features/copilot#pricing',
        lastVerified: '2025-01-15',
        notes: 'Annual billing: $100/year',
      },
      {
        planName: 'Business',
        monthlyPricePerSeat: 19,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: null,
        minSeats: null,
        features: ['Everything in Pro', 'Policy management', 'Audit logs', 'IP indemnity'],
        bestFor: ['small_team', 'mid_team'],
        sourceUrl: 'https://github.com/features/copilot#pricing',
        lastVerified: '2025-01-15',
        notes: null,
      },
      {
        planName: 'Enterprise',
        monthlyPricePerSeat: 39,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: null,
        minSeats: null,
        features: ['Everything in Business', 'Custom models', 'Knowledge bases', 'Repo indexing'],
        bestFor: ['mid_team', 'large_team'],
        sourceUrl: 'https://github.com/features/copilot#pricing',
        lastVerified: '2025-01-15',
        notes: null,
      },
    ],
  },
  {
    id: 'gemini',
    name: 'Gemini',
    category: 'ai_assistant',
    description: 'AI assistant by Google, strong Google Workspace integration',
    overlaps: ['chatgpt', 'claude'],
    plans: [
      {
        planName: 'Free',
        monthlyPricePerSeat: 0,
        flatMonthlyPrice: 0,
        annualMonthlyEquivalent: null,
        maxSeats: 1,
        minSeats: null,
        features: ['Gemini 1.5 Flash', 'Basic features', 'Google app integration'],
        bestFor: ['solo_developer'],
        sourceUrl: 'https://one.google.com/about/plans',
        lastVerified: '2025-01-15',
        notes: null,
      },
      {
        planName: 'Advanced',
        monthlyPricePerSeat: 19.99,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: 1,
        minSeats: null,
        features: ['Gemini 1.5 Pro', '2TB Google storage', 'Deep integration with Workspace'],
        bestFor: ['solo_developer'],
        sourceUrl: 'https://one.google.com/about/plans',
        lastVerified: '2025-01-15',
        notes: 'Part of Google One AI Premium',
      },
      {
        planName: 'Business',
        monthlyPricePerSeat: 24,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: null,
        minSeats: null,
        features: ['Gemini for Workspace', 'Admin controls', 'Enterprise security'],
        bestFor: ['small_team', 'mid_team'],
        sourceUrl: 'https://workspace.google.com/products/gemini/',
        lastVerified: '2025-01-15',
        notes: 'Requires Google Workspace subscription',
      },
    ],
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    category: 'ai_coding',
    description: 'AI code editor by Codeium with agentic coding features',
    overlaps: ['cursor', 'github_copilot'],
    plans: [
      {
        planName: 'Free',
        monthlyPricePerSeat: 0,
        flatMonthlyPrice: 0,
        annualMonthlyEquivalent: null,
        maxSeats: 1,
        minSeats: null,
        features: ['Unlimited completions', '5 user prompt credits/month', 'Basic Cascade'],
        bestFor: ['solo_developer'],
        sourceUrl: 'https://codeium.com/windsurf/pricing',
        lastVerified: '2025-01-15',
        notes: 'Generous free tier for completions',
      },
      {
        planName: 'Pro',
        monthlyPricePerSeat: 15,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: 1,
        minSeats: null,
        features: ['Unlimited completions', '500 user prompt credits/month', 'Full Cascade access'],
        bestFor: ['solo_developer', 'small_team'],
        sourceUrl: 'https://codeium.com/windsurf/pricing',
        lastVerified: '2025-01-15',
        notes: null,
      },
      {
        planName: 'Teams',
        monthlyPricePerSeat: 30,
        flatMonthlyPrice: null,
        annualMonthlyEquivalent: null,
        maxSeats: null,
        minSeats: 2,
        features: ['Everything in Pro', 'Team admin', 'Centralized billing', 'Priority support'],
        bestFor: ['small_team', 'mid_team'],
        sourceUrl: 'https://codeium.com/windsurf/pricing',
        lastVerified: '2025-01-15',
        notes: null,
      },
    ],
  },
]
